# Generated by Django 5.2 on 2026-07-08 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesheet',
            name='key_column_index',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='key_max_depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
