# Generated by Django 5.2.15 on 2026-07-08 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0002_templatesheet_key_column_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesheet',
            name='progress_actual_field_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='progress_plan_field_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
