# Generated by Django 5.2.15 on 2026-07-09 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0003_templatesheet_progress_actual_field_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesheet',
            name='progress_actual_field_key',
        ),
        migrations.RemoveField(
            model_name='templatesheet',
            name='progress_plan_field_key',
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='progress_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
