# Generated by Django 5.2.15 on 2026-07-20 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0004_remove_templatesheet_progress_actual_field_key_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesheet',
            name='label_field_key',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
