# Generated by Django 5.2.15 on 2026-07-28 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0005_templatesheet_label_field_key'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesheet',
            name='label_field_key',
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='label_field_keys',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
