# Generated by Django 5.2.15 on 2026-07-30 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0006_remove_templatesheet_label_field_key_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='templatesheet',
            name='key_column_index',
        ),
        migrations.RemoveField(
            model_name='templatesheet',
            name='key_max_depth',
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='key_column_indexes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='templatesheet',
            name='key_depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
