# Generated by Django 5.2.15 on 2026-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('templates', '0007_remove_templatesheet_key_column_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='templatesheet',
            name='total_row_labels',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
