# Generated by Django 5.2 on 2026-07-08 02:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportRow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sheet_name', models.CharField(max_length=200)),
                ('row_number', models.PositiveIntegerField()),
                ('data', models.JSONField()),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rows', to='reports.report')),
            ],
            options={
                'ordering': ['sheet_name', 'row_number'],
            },
        ),
    ]
