# Generated by Django 5.2.15 on 2026-07-28 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_reportrow'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrow',
            name='is_leaf',
            field=models.BooleanField(default=True),
        ),
    ]
