# Generated by Django 5.2.15 on 2026-08-03 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_reportrow_is_leaf'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrow',
            name='group_depth',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='reportrow',
            name='group_number',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
