# Generated by Django 5.2.15 on 2026-08-10 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0004_reportrow_group_depth_reportrow_group_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportrow',
            name='is_total_row',
            field=models.BooleanField(default=False),
        ),
    ]
